// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzqsTcjyIJP1gji-M6X4FrcgLhRp4Cxg0',
    appId: '1:991194243527:web:a03278c32cea7ed004f9e2',
    messagingSenderId: '991194243527',
    projectId: 'manga-7f0f9',
    authDomain: 'manga-7f0f9.firebaseapp.com',
    storageBucket: 'manga-7f0f9.firebasestorage.app',
    measurementId: 'G-YVCGZVN3JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVh8xaeEO9zza07gV1yDz55dMlEHGnVSs',
    appId: '1:991194243527:android:8fb3486712734df504f9e2',
    messagingSenderId: '991194243527',
    projectId: 'manga-7f0f9',
    storageBucket: 'manga-7f0f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgWrJPrJX5enw8Ia3D7AD0IZ4Zp3zjxP0',
    appId: '1:991194243527:ios:185d271cb0cd712804f9e2',
    messagingSenderId: '991194243527',
    projectId: 'manga-7f0f9',
    storageBucket: 'manga-7f0f9.firebasestorage.app',
    iosBundleId: 'com.example.togetherso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgWrJPrJX5enw8Ia3D7AD0IZ4Zp3zjxP0',
    appId: '1:991194243527:ios:185d271cb0cd712804f9e2',
    messagingSenderId: '991194243527',
    projectId: 'manga-7f0f9',
    storageBucket: 'manga-7f0f9.firebasestorage.app',
    iosBundleId: 'com.example.togetherso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzqsTcjyIJP1gji-M6X4FrcgLhRp4Cxg0',
    appId: '1:991194243527:web:b02e1421e2fbf5d604f9e2',
    messagingSenderId: '991194243527',
    projectId: 'manga-7f0f9',
    authDomain: 'manga-7f0f9.firebaseapp.com',
    storageBucket: 'manga-7f0f9.firebasestorage.app',
    measurementId: 'G-3SFXHCJ18H',
  );
}
